// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/catalog/v1/catalog.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetTrackByID_FullMethodName    = "/catalog.v1.CatalogService/GetTrackByID"
	CatalogService_TrackExists_FullMethodName     = "/catalog.v1.CatalogService/TrackExists"
	CatalogService_SearchTrack_FullMethodName     = "/catalog.v1.CatalogService/SearchTrack"
	CatalogService_GetArtistByID_FullMethodName   = "/catalog.v1.CatalogService/GetArtistByID"
	CatalogService_SearchArtist_FullMethodName    = "/catalog.v1.CatalogService/SearchArtist"
	CatalogService_GetArtistAlbums_FullMethodName = "/catalog.v1.CatalogService/GetArtistAlbums"
	CatalogService_GetArtistTracks_FullMethodName = "/catalog.v1.CatalogService/GetArtistTracks"
	CatalogService_GetAlbumByID_FullMethodName    = "/catalog.v1.CatalogService/GetAlbumByID"
	CatalogService_GetAlbumTracks_FullMethodName  = "/catalog.v1.CatalogService/GetAlbumTracks"
	CatalogService_ListTracks_FullMethodName      = "/catalog.v1.CatalogService/ListTracks"
	CatalogService_Health_FullMethodName          = "/catalog.v1.CatalogService/Health"
	CatalogService_GetLogs_FullMethodName         = "/catalog.v1.CatalogService/GetLogs"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error)
	TrackExists(ctx context.Context, in *TrackExistsRequest, opts ...grpc.CallOption) (*TrackExistsResponse, error)
	SearchTrack(ctx context.Context, in *SearchTrackRequest, opts ...grpc.CallOption) (*SearchTrackResponse, error)
	GetArtistByID(ctx context.Context, in *GetArtistByIDRequest, opts ...grpc.CallOption) (*GetArtistByIDResponse, error)
	SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*SearchArtistResponse, error)
	GetArtistAlbums(ctx context.Context, in *GetArtistAlbumsRequest, opts ...grpc.CallOption) (*GetArtistAlbumsResponse, error)
	GetArtistTracks(ctx context.Context, in *GetArtistTracksRequest, opts ...grpc.CallOption) (*GetArtistTracksResponse, error)
	GetAlbumByID(ctx context.Context, in *GetAlbumByIDRequest, opts ...grpc.CallOption) (*GetAlbumByIDResponse, error)
	GetAlbumTracks(ctx context.Context, in *GetAlbumTracksRequest, opts ...grpc.CallOption) (*GetAlbumTracksResponse, error)
	// Полный список треков каталога с пагинацией и фильтром по explicit
	// (0 — все, 1 — только с меткой, 2 — только без метки), с общим счётчиком.
	ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksResponse, error)
	// Проверка зависимостей catalog_service: postgres.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Последние записи внутреннего журнала сервиса (кольцевой буфер в памяти).
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetTrackByID(ctx context.Context, in *GetTrackByIDRequest, opts ...grpc.CallOption) (*GetTrackByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackByIDResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetTrackByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) TrackExists(ctx context.Context, in *TrackExistsRequest, opts ...grpc.CallOption) (*TrackExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackExistsResponse)
	err := c.cc.Invoke(ctx, CatalogService_TrackExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchTrack(ctx context.Context, in *SearchTrackRequest, opts ...grpc.CallOption) (*SearchTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTrackResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetArtistByID(ctx context.Context, in *GetArtistByIDRequest, opts ...grpc.CallOption) (*GetArtistByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistByIDResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetArtistByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*SearchArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtistResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetArtistAlbums(ctx context.Context, in *GetArtistAlbumsRequest, opts ...grpc.CallOption) (*GetArtistAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistAlbumsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetArtistAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetArtistTracks(ctx context.Context, in *GetArtistTracksRequest, opts ...grpc.CallOption) (*GetArtistTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetArtistTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlbumByID(ctx context.Context, in *GetAlbumByIDRequest, opts ...grpc.CallOption) (*GetAlbumByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlbumByIDResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAlbumByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetAlbumTracks(ctx context.Context, in *GetAlbumTracksRequest, opts ...grpc.CallOption) (*GetAlbumTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlbumTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetAlbumTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListTracks(ctx context.Context, in *ListTracksRequest, opts ...grpc.CallOption) (*ListTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTracksResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CatalogService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error)
	TrackExists(context.Context, *TrackExistsRequest) (*TrackExistsResponse, error)
	SearchTrack(context.Context, *SearchTrackRequest) (*SearchTrackResponse, error)
	GetArtistByID(context.Context, *GetArtistByIDRequest) (*GetArtistByIDResponse, error)
	SearchArtist(context.Context, *SearchArtistRequest) (*SearchArtistResponse, error)
	GetArtistAlbums(context.Context, *GetArtistAlbumsRequest) (*GetArtistAlbumsResponse, error)
	GetArtistTracks(context.Context, *GetArtistTracksRequest) (*GetArtistTracksResponse, error)
	GetAlbumByID(context.Context, *GetAlbumByIDRequest) (*GetAlbumByIDResponse, error)
	GetAlbumTracks(context.Context, *GetAlbumTracksRequest) (*GetAlbumTracksResponse, error)
	// Полный список треков каталога с пагинацией и фильтром по explicit
	// (0 — все, 1 — только с меткой, 2 — только без метки), с общим счётчиком.
	ListTracks(context.Context, *ListTracksRequest) (*ListTracksResponse, error)
	// Проверка зависимостей catalog_service: postgres.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Последние записи внутреннего журнала сервиса (кольцевой буфер в памяти).
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetTrackByID(context.Context, *GetTrackByIDRequest) (*GetTrackByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackByID not implemented")
}
func (UnimplementedCatalogServiceServer) TrackExists(context.Context, *TrackExistsRequest) (*TrackExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackExists not implemented")
}
func (UnimplementedCatalogServiceServer) SearchTrack(context.Context, *SearchTrackRequest) (*SearchTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTrack not implemented")
}
func (UnimplementedCatalogServiceServer) GetArtistByID(context.Context, *GetArtistByIDRequest) (*GetArtistByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistByID not implemented")
}
func (UnimplementedCatalogServiceServer) SearchArtist(context.Context, *SearchArtistRequest) (*SearchArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtist not implemented")
}
func (UnimplementedCatalogServiceServer) GetArtistAlbums(context.Context, *GetArtistAlbumsRequest) (*GetArtistAlbumsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistAlbums not implemented")
}
func (UnimplementedCatalogServiceServer) GetArtistTracks(context.Context, *GetArtistTracksRequest) (*GetArtistTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtistTracks not implemented")
}
func (UnimplementedCatalogServiceServer) GetAlbumByID(context.Context, *GetAlbumByIDRequest) (*GetAlbumByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbumByID not implemented")
}
func (UnimplementedCatalogServiceServer) GetAlbumTracks(context.Context, *GetAlbumTracksRequest) (*GetAlbumTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbumTracks not implemented")
}
func (UnimplementedCatalogServiceServer) ListTracks(context.Context, *ListTracksRequest) (*ListTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTracks not implemented")
}
func (UnimplementedCatalogServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCatalogServiceServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetTrackByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetTrackByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetTrackByID(ctx, req.(*GetTrackByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_TrackExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).TrackExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_TrackExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).TrackExists(ctx, req.(*TrackExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchTrack(ctx, req.(*SearchTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetArtistByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetArtistByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetArtistByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetArtistByID(ctx, req.(*GetArtistByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchArtist(ctx, req.(*SearchArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetArtistAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetArtistAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetArtistAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetArtistAlbums(ctx, req.(*GetArtistAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetArtistTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetArtistTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetArtistTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetArtistTracks(ctx, req.(*GetArtistTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlbumByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlbumByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAlbumByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlbumByID(ctx, req.(*GetAlbumByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetAlbumTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetAlbumTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetAlbumTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetAlbumTracks(ctx, req.(*GetAlbumTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListTracks(ctx, req.(*ListTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrackByID",
			Handler:    _CatalogService_GetTrackByID_Handler,
		},
		{
			MethodName: "TrackExists",
			Handler:    _CatalogService_TrackExists_Handler,
		},
		{
			MethodName: "SearchTrack",
			Handler:    _CatalogService_SearchTrack_Handler,
		},
		{
			MethodName: "GetArtistByID",
			Handler:    _CatalogService_GetArtistByID_Handler,
		},
		{
			MethodName: "SearchArtist",
			Handler:    _CatalogService_SearchArtist_Handler,
		},
		{
			MethodName: "GetArtistAlbums",
			Handler:    _CatalogService_GetArtistAlbums_Handler,
		},
		{
			MethodName: "GetArtistTracks",
			Handler:    _CatalogService_GetArtistTracks_Handler,
		},
		{
			MethodName: "GetAlbumByID",
			Handler:    _CatalogService_GetAlbumByID_Handler,
		},
		{
			MethodName: "GetAlbumTracks",
			Handler:    _CatalogService_GetAlbumTracks_Handler,
		},
		{
			MethodName: "ListTracks",
			Handler:    _CatalogService_ListTracks_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CatalogService_Health_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _CatalogService_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog/v1/catalog.proto",
}

const (
	CatalogWriteService_AddArtist_FullMethodName         = "/catalog.v1.CatalogWriteService/AddArtist"
	CatalogWriteService_AddAlbum_FullMethodName          = "/catalog.v1.CatalogWriteService/AddAlbum"
	CatalogWriteService_AddTrack_FullMethodName          = "/catalog.v1.CatalogWriteService/AddTrack"
	CatalogWriteService_AddTracksToAlbum_FullMethodName  = "/catalog.v1.CatalogWriteService/AddTracksToAlbum"
	CatalogWriteService_IncrementListened_FullMethodName = "/catalog.v1.CatalogWriteService/IncrementListened"
	CatalogWriteService_SetAlbumCover_FullMethodName     = "/catalog.v1.CatalogWriteService/SetAlbumCover"
	CatalogWriteService_SetTrackCover_FullMethodName     = "/catalog.v1.CatalogWriteService/SetTrackCover"
	CatalogWriteService_SetTrackExplicit_FullMethodName  = "/catalog.v1.CatalogWriteService/SetTrackExplicit"
	CatalogWriteService_DeleteTrack_FullMethodName       = "/catalog.v1.CatalogWriteService/DeleteTrack"
	CatalogWriteService_DeleteAlbum_FullMethodName       = "/catalog.v1.CatalogWriteService/DeleteAlbum"
)

// CatalogWriteServiceClient is the client API for CatalogWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// вынесен в отдельный gRPC-сервис (свой порт), чтобы write-путь
// можно было изолировать от read-пути на уровне сети
type CatalogWriteServiceClient interface {
	AddArtist(ctx context.Context, in *AddArtistRequest, opts ...grpc.CallOption) (*AddArtistResponse, error)
	AddAlbum(ctx context.Context, in *AddAlbumRequest, opts ...grpc.CallOption) (*AddAlbumResponse, error)
	AddTrack(ctx context.Context, in *AddTrackRequest, opts ...grpc.CallOption) (*AddTrackResponse, error)
	AddTracksToAlbum(ctx context.Context, in *AddTracksToAlbumRequest, opts ...grpc.CallOption) (*AddTracksToAlbumResponse, error)
	IncrementListened(ctx context.Context, in *IncrementListenedRequest, opts ...grpc.CallOption) (*IncrementListenedResponse, error)
	SetAlbumCover(ctx context.Context, in *SetAlbumCoverRequest, opts ...grpc.CallOption) (*SetAlbumCoverResponse, error)
	SetTrackCover(ctx context.Context, in *SetTrackCoverRequest, opts ...grpc.CallOption) (*SetTrackCoverResponse, error)
	// Смена метки 18+ у существующего трека (модерация из админки).
	SetTrackExplicit(ctx context.Context, in *SetTrackExplicitRequest, opts ...grpc.CallOption) (*SetTrackExplicitResponse, error)
	DeleteTrack(ctx context.Context, in *DeleteTrackRequest, opts ...grpc.CallOption) (*DeleteTrackResponse, error)
	DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error)
}

type catalogWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogWriteServiceClient(cc grpc.ClientConnInterface) CatalogWriteServiceClient {
	return &catalogWriteServiceClient{cc}
}

func (c *catalogWriteServiceClient) AddArtist(ctx context.Context, in *AddArtistRequest, opts ...grpc.CallOption) (*AddArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddArtistResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_AddArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) AddAlbum(ctx context.Context, in *AddAlbumRequest, opts ...grpc.CallOption) (*AddAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAlbumResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_AddAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) AddTrack(ctx context.Context, in *AddTrackRequest, opts ...grpc.CallOption) (*AddTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTrackResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_AddTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) AddTracksToAlbum(ctx context.Context, in *AddTracksToAlbumRequest, opts ...grpc.CallOption) (*AddTracksToAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTracksToAlbumResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_AddTracksToAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) IncrementListened(ctx context.Context, in *IncrementListenedRequest, opts ...grpc.CallOption) (*IncrementListenedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementListenedResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_IncrementListened_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) SetAlbumCover(ctx context.Context, in *SetAlbumCoverRequest, opts ...grpc.CallOption) (*SetAlbumCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAlbumCoverResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_SetAlbumCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) SetTrackCover(ctx context.Context, in *SetTrackCoverRequest, opts ...grpc.CallOption) (*SetTrackCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTrackCoverResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_SetTrackCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) SetTrackExplicit(ctx context.Context, in *SetTrackExplicitRequest, opts ...grpc.CallOption) (*SetTrackExplicitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTrackExplicitResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_SetTrackExplicit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) DeleteTrack(ctx context.Context, in *DeleteTrackRequest, opts ...grpc.CallOption) (*DeleteTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTrackResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_DeleteTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogWriteServiceClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*DeleteAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlbumResponse)
	err := c.cc.Invoke(ctx, CatalogWriteService_DeleteAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogWriteServiceServer is the server API for CatalogWriteService service.
// All implementations must embed UnimplementedCatalogWriteServiceServer
// for forward compatibility.
//
// вынесен в отдельный gRPC-сервис (свой порт), чтобы write-путь
// можно было изолировать от read-пути на уровне сети
type CatalogWriteServiceServer interface {
	AddArtist(context.Context, *AddArtistRequest) (*AddArtistResponse, error)
	AddAlbum(context.Context, *AddAlbumRequest) (*AddAlbumResponse, error)
	AddTrack(context.Context, *AddTrackRequest) (*AddTrackResponse, error)
	AddTracksToAlbum(context.Context, *AddTracksToAlbumRequest) (*AddTracksToAlbumResponse, error)
	IncrementListened(context.Context, *IncrementListenedRequest) (*IncrementListenedResponse, error)
	SetAlbumCover(context.Context, *SetAlbumCoverRequest) (*SetAlbumCoverResponse, error)
	SetTrackCover(context.Context, *SetTrackCoverRequest) (*SetTrackCoverResponse, error)
	// Смена метки 18+ у существующего трека (модерация из админки).
	SetTrackExplicit(context.Context, *SetTrackExplicitRequest) (*SetTrackExplicitResponse, error)
	DeleteTrack(context.Context, *DeleteTrackRequest) (*DeleteTrackResponse, error)
	DeleteAlbum(context.Context, *DeleteAlbumRequest) (*DeleteAlbumResponse, error)
	mustEmbedUnimplementedCatalogWriteServiceServer()
}

// UnimplementedCatalogWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogWriteServiceServer struct{}

func (UnimplementedCatalogWriteServiceServer) AddArtist(context.Context, *AddArtistRequest) (*AddArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddArtist not implemented")
}
func (UnimplementedCatalogWriteServiceServer) AddAlbum(context.Context, *AddAlbumRequest) (*AddAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAlbum not implemented")
}
func (UnimplementedCatalogWriteServiceServer) AddTrack(context.Context, *AddTrackRequest) (*AddTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrack not implemented")
}
func (UnimplementedCatalogWriteServiceServer) AddTracksToAlbum(context.Context, *AddTracksToAlbumRequest) (*AddTracksToAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTracksToAlbum not implemented")
}
func (UnimplementedCatalogWriteServiceServer) IncrementListened(context.Context, *IncrementListenedRequest) (*IncrementListenedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementListened not implemented")
}
func (UnimplementedCatalogWriteServiceServer) SetAlbumCover(context.Context, *SetAlbumCoverRequest) (*SetAlbumCoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAlbumCover not implemented")
}
func (UnimplementedCatalogWriteServiceServer) SetTrackCover(context.Context, *SetTrackCoverRequest) (*SetTrackCoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrackCover not implemented")
}
func (UnimplementedCatalogWriteServiceServer) SetTrackExplicit(context.Context, *SetTrackExplicitRequest) (*SetTrackExplicitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrackExplicit not implemented")
}
func (UnimplementedCatalogWriteServiceServer) DeleteTrack(context.Context, *DeleteTrackRequest) (*DeleteTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrack not implemented")
}
func (UnimplementedCatalogWriteServiceServer) DeleteAlbum(context.Context, *DeleteAlbumRequest) (*DeleteAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAlbum not implemented")
}
func (UnimplementedCatalogWriteServiceServer) mustEmbedUnimplementedCatalogWriteServiceServer() {}
func (UnimplementedCatalogWriteServiceServer) testEmbeddedByValue()                             {}

// UnsafeCatalogWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogWriteServiceServer will
// result in compilation errors.
type UnsafeCatalogWriteServiceServer interface {
	mustEmbedUnimplementedCatalogWriteServiceServer()
}

func RegisterCatalogWriteServiceServer(s grpc.ServiceRegistrar, srv CatalogWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogWriteService_ServiceDesc, srv)
}

func _CatalogWriteService_AddArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).AddArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_AddArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).AddArtist(ctx, req.(*AddArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_AddAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).AddAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_AddAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).AddAlbum(ctx, req.(*AddAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_AddTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).AddTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_AddTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).AddTrack(ctx, req.(*AddTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_AddTracksToAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTracksToAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).AddTracksToAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_AddTracksToAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).AddTracksToAlbum(ctx, req.(*AddTracksToAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_IncrementListened_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementListenedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).IncrementListened(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_IncrementListened_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).IncrementListened(ctx, req.(*IncrementListenedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_SetAlbumCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlbumCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).SetAlbumCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_SetAlbumCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).SetAlbumCover(ctx, req.(*SetAlbumCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_SetTrackCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrackCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).SetTrackCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_SetTrackCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).SetTrackCover(ctx, req.(*SetTrackCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_SetTrackExplicit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrackExplicitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).SetTrackExplicit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_SetTrackExplicit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).SetTrackExplicit(ctx, req.(*SetTrackExplicitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_DeleteTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).DeleteTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_DeleteTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).DeleteTrack(ctx, req.(*DeleteTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogWriteService_DeleteAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogWriteServiceServer).DeleteAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogWriteService_DeleteAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogWriteServiceServer).DeleteAlbum(ctx, req.(*DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogWriteService_ServiceDesc is the grpc.ServiceDesc for CatalogWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogWriteService",
	HandlerType: (*CatalogWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddArtist",
			Handler:    _CatalogWriteService_AddArtist_Handler,
		},
		{
			MethodName: "AddAlbum",
			Handler:    _CatalogWriteService_AddAlbum_Handler,
		},
		{
			MethodName: "AddTrack",
			Handler:    _CatalogWriteService_AddTrack_Handler,
		},
		{
			MethodName: "AddTracksToAlbum",
			Handler:    _CatalogWriteService_AddTracksToAlbum_Handler,
		},
		{
			MethodName: "IncrementListened",
			Handler:    _CatalogWriteService_IncrementListened_Handler,
		},
		{
			MethodName: "SetAlbumCover",
			Handler:    _CatalogWriteService_SetAlbumCover_Handler,
		},
		{
			MethodName: "SetTrackCover",
			Handler:    _CatalogWriteService_SetTrackCover_Handler,
		},
		{
			MethodName: "SetTrackExplicit",
			Handler:    _CatalogWriteService_SetTrackExplicit_Handler,
		},
		{
			MethodName: "DeleteTrack",
			Handler:    _CatalogWriteService_DeleteTrack_Handler,
		},
		{
			MethodName: "DeleteAlbum",
			Handler:    _CatalogWriteService_DeleteAlbum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog/v1/catalog.proto",
}
